services:
  - type: web
    name: dentsu-md-v10
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: BOT_NAME
        value: "DENTSU MD V10"
      - key: DEV_NAME
        value: "natsu242"
      - key: PREFIX
        value: "."
      - key: MODE
        value: "public"
      - key: OWNER_NUMBER
        value: "242065121108"
      - key: MENU_IMAGE
        value: "https://raw.githubusercontent.com/kinggggg444/DENTSU-MD-V10/main/assets/bot-avatar.png"
      - key: CHANNEL_LINK
        value: "https://whatsapp.com/channel/0029VbC1s7fFnSz1YhZYc01h"
      - key: GROUP_LINK
        value: "https://chat.whatsapp.com/GtXASqDdchAFvEJ95cQQ0F"
      - key: CHANNEL_LINK2
        value: "https://whatsapp.com/channel/0029VayOeIbGufIvDPhi6m1X"
      - key: TELEGRAM
        value: "https://t.me/Natsu_or_Dentsu"
      - key: WEBSITE
        value: "https://dentsu-md-v10.onrender.com"
      - key: MAX_SESSIONS
        value: "50"
      - key: NODE_ENV
        value: "production"
    healthCheckPath: /health
